# vim ft=yaml
# travis-ci.org definition for MOxUnit build (based on CoSMoMVPA,
# which is based on PyMVPA, which is based on nipype configuration, 
# which in turn was based on nipy)
#
# We pretend to be java because we need GNU Octave which is not
# available (as of April 2015)

language: java

cache:
  - apt
env:
 global:
    - OCTAVE=octave
 matrix:
    - WITH_COVERAGE=
    - WITH_COVERAGE=true
    - RUN_DOC_TEST=true
before_install:
    # to prevent IPv6 being used for APT
    - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
    - travis_retry sudo apt-get -y -qq update
    - travis_retry sudo apt-get install -y -qq software-properties-common python-software-properties
    - travis_retry sudo apt-add-repository -y ppa:octave/stable
    - travis_retry sudo apt-get -y -qq update
    # get Octave 4,0
    - travis_retry sudo apt-get -y -qq install octave liboctave-dev
    # install MOxUnit
    - cd ..
    - rm -rf MOxUnit
    - git clone https://github.com/MOxUnit/MOxUnit.git
    - make -C MOxUnit install
    # install MOdox
    - cd ..
    - rm -rf MOdox
    - git clone https://github.com/MOdox/MOdox.git
    - make -C MOdox install
    # install MOcov
    - cd ..
    - rm -rf MOcov
    - git clone https://github.com/MOcov/MOcov.git
    - make -C MOcov install
    
script:
    - pwd
    - dir
    - cd /home/travis/build/DelfiSpace/ThermalModel
    - octave --no-gui --eval "addpath('/home/travis/build/DelfiSpace/MOxUnit/MOxUnit');moxunit_set_path;moxunit_runtests('tests')"
    
